// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvztokbjkaosjxnziizt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2enRva2Jqa2Fvc2p4bnppaXp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MDE3NzQsImV4cCI6MjA2MjE3Nzc3NH0.15zzJ2TzY15EKYxZK1jHcgMeFVCnilH9UkDYR-y-5gY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});